// This file is auto-generated by Velite after running `npm run build` or `velite build`.
// It re-exports the typed content from .velite/index.ts
// TypeScript resolves the `@site/content` path alias via tsconfig.json paths.

export * from '../.velite'
