/**
 * Velite generates types from the schema + transforms at build time.
 * The `readingTime` field is added by our `.transform()` in velite.config.ts.
 *
 * Until `.velite/` is generated by the first build, we use this augmented type
 * to keep TypeScript happy in editors.
 */
export type PostWithMeta = {
  title: string
  slug: string
  date: string
  description: string
  tags: string[]
  published: boolean
  coverImage?: string
  permalink: string
  readingTime: string
  body: {
    code: string
    raw?: string
  }
}
